[project]
name = "resume-maker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "motor",
    "beanie",
    "bcrypt",
    "python-jose[cryptography]",
    "python-dotenv",
    "weasyprint",
    "pydantic[email]",
    "bcrypt"
]

[tool.vercel]
entrypoint = "backend.main:app"